# Server im using cant do a build due to low memory, so I push the build and this just moves the files to the correct directory

name: Move build files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Move build files
    - run: cp dist/* /var/www/portfolio4/ -r
